spring.datasource.url=jdbc:h2:mem:usersdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.h2.console.enabled=true

jwt.secret=bci-secret-key-2024-very-long-and-secure
jwt.expiration=86400000

spring.security.user.name=user
spring.security.user.password=password